In [1]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1,2,3] * [1,2,3]

TypeError: can't multiply sequence by non-int of type 'list'

makanya butuh numpy (numerical python)

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

a * 3

array([3, 6, 9])

In [5]:
np.sum([1,2,3])

6

In [6]:
np.std(a)

0.816496580927726

In [7]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

arange, linspace, logspace

In [8]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

In [24]:
np.random.rand(3,2)

array([[0.86408076, 0.24492575],
       [0.18025966, 0.45443664],
       [0.48281423, 0.28698232]])

In [25]:
a = np.random.RandomState(42)

In [26]:
a.rand(3,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452]])